Allow options like "timeout" to be passed to HTTPoison.get_blob underneath inside `options`
jakobht/azurex pull request #54
Opened 2024-09-02 08:55 UTC by krishna1m

Fixes #53 

Allows to call the new signature like below -
```
Azurex.Blob.get_blob(name, container, recv_timeout: 60_000, timeout: 60_000, headers: [{"Content-Type", "application/json"}])
```

2024-10-25 18:34 UTC, mattpolzin commented
Was it necessary to add the config element changes in the same PR? At first glance they look like separate goals. I'm not a maintainer, just asking the question.

2024-10-28 08:44 UTC, craigfurman commented
@mattpolzin sorry, these are definitely separate goals. When I recently committed to this fork's master branch the other day, I had no idea this PR existed.

@krishna1m let's close this, cut a branch before that recent fork commit, and PR that. If that lands, we can PR the config bit separately. WDYT?

2025-05-11 10:40 UTC, jakobht requested changes
I like the intention of this, but as far as I can see it breaks backwards compatibility. I would very much like to avoid that, since that would force everyone to update all their calls.

2025-05-11 10:40 UTC, jakobht commented on test/integration/blob_integration_test.exs
> +               container: @integration_testing_container
I get why we would want to change this, but it would break compatibility, is it possible to avoid this?

2025-05-11 10:40 UTC, jakobht commented on test/integration/blob_integration_test.exs
> +               ]
Same comment as above, this breaks compatability

2025-05-12 08:18 UTC, closed without merging